version: "3.3"

networks:
    traefik_macvlan:
        driver: macvlan
        driver_opts:
            parent: eth0
        ipam:
            config:
                - subnet: 192.168.178.0/24
                  ip_range: 192.168.178.192/27
                  gateway: "192.168.178.1"

services:
    watchtower:
        image: containrrr/watchtower
        env_file: .env
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
    traefik:
        image: "traefik:v2.5"
        restart: unless-stopped
        networks:
            traefik_macvlan:
                ipv4_address: "192.168.178.193"
        command:
            - "--configFile=/traefik/config.yml"
        dns:
            - "1.1.1.1"
        ports:
            - "80:80"
            - "443:443"
            - "8080:8080"
        env_file: .env
        volumes:
            - "/volume1/WD1/home/traefik/letsencrypt:/letsencrypt"
            - "/volume1/WD1/home/home/traefik:/traefik"
            - "/var/run/docker.sock:/var/run/docker.sock:ro"
    jdownloader:
        image: jlesage/jdownloader-2:latest
        restart: unless-stopped
        ports:
            - "5800:5800"
        dns:
            - "1.1.1.1"
        environment:
            USER_ID: 1000
            GROUP_ID: 1000
            APP_USER: app
        volumes:
            - "/volume1/WD1/home/jdownloader:/config"
            - "/volume1/WD1/Downloads:/output"
    plex:
        image: lscr.io/linuxserver/plex
        restart: unless-stopped
        dns:
            - "1.1.1.1"
        network_mode: "host"
        environment:
            - PUID=1000
            - PGID=1000
            - VERSION=docker
        volumes:
            - /volume1/WD1/home/plex:/config
            - /volume1/WD1/Movies:/movies
            - /volume1/WD1/Shows:/shows
            - /volume1/WD1/Music:/music
            - /volume1/WD1/Audiobooks:/audibooks