version: "3.3"

networks:
  traefik_macvlan:
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: 192.168.178.0/24
          ip_range: 192.168.178.192/27
          gateway: "192.168.178.1"

services:
  traefik:
    image: "traefik:v2.5"
    container_name: "traefik"
    networks:
        traefik_macvlan:
          ipv4_address: "192.168.178.193"
    command:
      - "--configFile=/traefik/config.yml"
    dns:
      - "1.1.1.1"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    env_file: .env
    volumes:
      - "/volume1/WD1/home/traefik/letsencrypt:/letsencrypt"
      - "/volume1/WD1/home/home/traefik:/traefik"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
