entryPoints:
  plex:
    address: ":32400"
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    address: ":443"

serversTransport:
  insecureSkipVerify: true

api:
  insecure: true
  dashboard: true

log:
  level: INFO

certificatesResolvers:
  cloudflare:
    acme:
      email: daniel.pasch.s@gmail.com
      storage: /letsencrypt/acme.json
      dnsChallenge:
        provider: cloudflare
        delayBeforeCheck: 0

providers:
  file:
    directory: /traefik/rules