http:
  middlewares:
    grafana_auth:
      headers:
        customRequestHeaders:
          X-WEBAUTH-USER: "admin"
  routers:
    traefik:
      rule: "Host(`traefik.i.gempir.com`)"
      service: traefik
      tls:
        certResolver: cloudflare
    vacuum:
      rule: "Host(`vacuum.i.gempir.com`)"
      service: vacuum
      tls:
        certResolver: cloudflare
    synology:
      rule: "Host(`synology.i.gempir.com`)"
      service: synology
      tls:
        certResolver: cloudflare
    plex:
      rule: "Host(`plex.i.gempir.com`)"
      service: plex
      tls:
        certResolver: cloudflare
    fritz:
      rule: "Host(`fritz.i.gempir.com`)"
      service: fritz
      tls:
        certResolver: cloudflare
    jdownloader:
      rule: "Host(`jdownloader.i.gempir.com`)"
      service: jdownloader
      tls:
        certResolver: cloudflare
    media_power:
      rule: "Host(`media-power.i.gempir.com`)"
      service: media_power
      tls:
        certResolver: cloudflare
    desk_power:
      rule: "Host(`desk-power.i.gempir.com`)"
      service: desk_power
      tls:
        certResolver: cloudflare
    wash_power:
      rule: "Host(`wash-power.i.gempir.com`)"
      service: wash_power
      tls:
        certResolver: cloudflare
    bathroom_mirror_light:
      rule: "Host(`bathroom-mirror-light.i.gempir.com`)"
      service: bathroom_mirror_light
      tls:
        certResolver: cloudflare
    falcon_light:
      rule: "Host(`falcon-light.i.gempir.com`)"
      service: falcon_light
      tls:
        certResolver: cloudflare
    screen_light:
      rule: "Host(`screen-light.i.gempir.com`)"
      service: screen_light
      tls:
        certResolver: cloudflare
  services:
    traefik:
      loadBalancer:
        servers:
          - url: "http://127.0.0.1:8080/"
    vacuum:
      loadBalancer:
        servers:
          - url: "http://192.168.178.38:80/"
    synology:
      loadBalancer:
        servers:
          - url: "https://192.168.178.194:5001/"
    plex:
      loadBalancer:
        servers:
          - url: "http://192.168.178.194:32400/"
    fritz:
      loadBalancer:
        servers:
          - url: "http://192.168.178.1:80/"
    jdownloader:
      loadBalancer:
        servers:
          - url: "http://192.168.178.194:5800/"
    media_power:
      loadBalancer:
        servers:
          - url: "http://192.168.178.29:80/"
    desk_power:
      loadBalancer:
        servers:
          - url: "http://192.168.178.32:80/"
    wash_power:
      loadBalancer:
        servers:
          - url: "http://192.168.178.37:80/"
    falcon_light:
      loadBalancer:
        servers:
          - url: "http://192.168.178.22:80/"
    bathroom_mirror_light:
      loadBalancer:
        servers:
          - url: "http://192.168.178.30:80/"
    screen_light:
      loadBalancer:
        servers:
          - url: "http://192.168.178.27:80/"