---
- name: setup base
  file:
    path: "{{ services_folder }}"
    state: directory
    mode: "0755"
    owner: "{{ services_user }}"
    group: "{{ services_user }}"

- name: setup services folders
  file:
    path: "{{ services_folder }}/{{ item }}"
    state: directory
    mode: "0755"
    owner: "{{ services_user }}"
    group: "{{ services_user }}"
  with_items:
    - mealie
    - adguard

- name: setup storage folders
  file:
    path: "{{ storage_folder }}/{{ item }}"
    state: directory
    mode: "0755"
    owner: "{{ services_user }}"
    group: "{{ services_user }}"
  with_items:
    - mealie
    - adguard

- name: create docker-compose
  template:
    src: docker-compose.yaml
    dest: "{{ services_folder }}/docker-compose.yaml"
    owner: "{{ services_user }}"
    group: "{{ services_user }}"
    mode: "0644"

- name: create env
  template:
    src: env
    dest: "{{ services_folder }}/.env"
    owner: "{{ services_user }}"
    group: "{{ services_user }}"
    mode: "0644"

- name: copy folders
  copy:
    src: files/{{ item }}
    dest: "{{ services_folder }}"
    owner: "{{ services_user }}"
    group: "{{ services_user }}"
    mode: "0644"
  with_items: 
    - adguard